[package]
name = "rusty-reel"
version = "0.0.1"
edition = "2024"
authors = [ "kaya" ]


[dependencies]
bevy = "^0.17.3"
bevy_rapier2d = { version = "^0.32.0", features = ["simd-nightly", "parallel"] }
rand = "^0.9.2"
rand_chacha = "0.9.0"